# Generated by Django 6.0.4 on 2026-04-21 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='data_entrada',
        ),
        migrations.AlterField(
            model_name='membro',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.escola'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='idade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='membro',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (99) 99999-9999 ou (99) 9999-9999.', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')]),
        ),
    ]
