# Generated by Django 6.0.4 on 2026-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordenador', 'Coordenador'), ('supervisor', 'Supervisor'), ('lider', 'Líder')], max_length=20),
        ),
    ]
