# Generated by Django 6.0.4 on 2026-04-17 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='coordenador_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'coordenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisores_vinculados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='supervisor_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lideres_vinculados', to=settings.AUTH_USER_MODEL),
        ),
    ]
