# Generated by Django 6.0.4 on 2026-04-21 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_coordenador_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (99) 99999-9999 ou (99) 9999-9999.', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')]),
        ),
    ]
