# Generated by Django 6.0.4 on 2026-04-16 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('multiplicado', 'Multiplicado')], default='ativo', max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='escolas.escola')),
                ('lider', models.ForeignKey(limit_choices_to={'tipo_usuario': 'lider'}, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_liderados', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'tipo_usuario': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_supervisionados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
