# Generated by Django 6.0.4 on 2026-04-16 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0001_initial'),
        ('membros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encontro', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encontros', to='grupos.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='frequencias.encontro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='membros.membro')),
            ],
            options={
                'unique_together': {('encontro', 'membro')},
            },
        ),
    ]
