# Generated by Django 6.0.4 on 2026-04-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencias', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encontro',
            unique_together={('grupo', 'data_encontro')},
        ),
    ]
